name: Build and Deploy to Azure Web App - Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: docker.io/kris888777/coverletter-app:latest

    - name: Deploy to Azure Web App (Docker)
      uses: azure/webapps-deploy@v3
      with:
        app-name: coverletter-generator
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: docker.io/kris888777/coverletter-app:latest